------------------------
2022-09-18 20:08:26,307 
------------------------
 /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: could not translate host name "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known

------------------------
2022-09-18 20:08:26,307 
------------------------
 /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: None
------------------------
2022-09-18 20:08:26,307 
------------------------
 /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 'NoneType' object has no attribute 'cursor'
------------------------
2022-09-18 20:09:53,666 
------------------------
 /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/db_connect.py: could not translate host name "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known

------------------------
2022-09-18 20:09:53,667 
------------------------
 /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/db_connect.py: None
------------------------
2022-09-18 20:09:53,667 
------------------------
 /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/db_connect.py: 'NoneType' object has no attribute 'cursor'
------------------------
2022-09-19 00:20:19,045 
------------------------
 extract.py: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 00:20:19,045 
------------------------
 extract.py: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 00:41:47,741 
------------------------
 db_connect.py: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 <connection object at 0x10873cc10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0>
------------------------
2022-09-19 00:42:10,776 
------------------------
 db_connect.py: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 <connection object at 0x10864cc10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0>
------------------------
2022-09-19 01:52:49,056 
------------------------
 extract.py: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 01:58:31,445 
------------------------
 extract.py:  /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:00:20,048 
------------------------
 extract.py:  handlers.log_handler: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:02:06,145 
------------------------
 extract.py:  /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:03:13,813 
------------------------
 db_connect.py:  /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/db_connect.py: 
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "<configparser.ConfigParser object at 0x10fd571c0>" does not exist

------------------------
2022-09-19 02:03:13,813 
------------------------
 db_connect.py:  /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/db_connect.py: 
 None
------------------------
2022-09-19 02:03:13,813 
------------------------
 db_connect.py:  /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/db_connect.py: 
 'NoneType' object has no attribute 'cursor'
------------------------
2022-09-19 02:04:11,089 
------------------------
 db_connect.py:  /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/db_connect.py: 
 <connection object at 0x10f921d20; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0>
------------------------
2022-09-19 02:07:46,013 
------------------------
 extract.py:  
             initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:08:53,651 
------------------------
 extract.py:  
             initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:08:53,651 
------------------------
 extract.py:  
             initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:10:14,606 
------------------------
 extract.py:  
             initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:10:14,606 
------------------------
 extract.py:  
             initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:11:20,409 
------------------------
 extract.py:  
             initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:11:20,409 
------------------------
 extract.py:  
             initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py: 
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data"
------------------------
2022-09-19 02:15:49,347 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data" @ 
  initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 02:15:49,347 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data" @ 
  initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 02:17:35,099 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data" 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 02:17:35,099 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.ohio.amazonaws.com/orders_data" 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 03:19:27,300 
------------------------
 db_connect.py:  
             
 <connection object at 0x118c313f0; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 04:29:36,563 
------------------------
 extract.py:  
             
 Unable to locate credentials 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 04:29:36,563 
------------------------
 extract.py:  
             
 Unable to locate credentials 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 04:31:27,249 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.Global.amazonaws.com/orders_data" 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 04:31:27,249 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.Global.amazonaws.com/orders_data" 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 05:59:18,294 
------------------------
 db_connect.py:  
             
 <connection object at 0x10cf986d0; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 05:59:51,252 
------------------------
 db_connect.py:  
             
 <connection object at 0x10bb0c6d0; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 11:14:51,887 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.Global.amazonaws.com/?prefix=orders_data&encoding-type=url" 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 11:14:51,887 
------------------------
 extract.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.Global.amazonaws.com/?prefix=orders_data&encoding-type=url" 
  @ initiate_s3: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 17:47:28,670 
------------------------
 extract.py:  
             
 download_file() missing 1 required positional argument: 'Filename' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 17:47:28,670 
------------------------
 extract.py:  
             
 download_file() missing 1 required positional argument: 'Filename' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 17:48:45,773 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 17:48:45,773 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 18:15:05,871 
------------------------
 extract.py:  
             
 [Errno 2] No such file or directory: '../Data2Bot-Assessment/assets/data/raw/orders.csv.9b340EF4' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 18:15:05,871 
------------------------
 extract.py:  
             
 [Errno 2] No such file or directory: '../Data2Bot-Assessment/assets/data/raw/orders.csv.9b340EF4' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:08:47,725 
------------------------
 db_connect.py:  
             
 <connection object at 0x10e648c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:08:49,870 
------------------------
 db_connect.py:  
             
 <connection object at 0x10e648d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:08:52,060 
------------------------
 db_connect.py:  
             
 <connection object at 0x10e648c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:08:54,070 
------------------------
 db_connect.py:  
             
 <connection object at 0x10e648d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:09:30,653 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:09:30,653 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:09:30,653 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:09:30,653 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:10:22,574 
------------------------
 db_connect.py:  
             
 <connection object at 0x108d34c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:10:25,128 
------------------------
 db_connect.py:  
             
 <connection object at 0x108d34d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:10:28,169 
------------------------
 db_connect.py:  
             
 <connection object at 0x108d34c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:10:30,177 
------------------------
 db_connect.py:  
             
 <connection object at 0x108d34d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:10:46,006 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:10:46,006 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:10:46,006 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:10:46,006 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:11:39,486 
------------------------
 db_connect.py:  
             
 <connection object at 0x106c98c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:11:41,437 
------------------------
 db_connect.py:  
             
 <connection object at 0x106c98d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:11:44,483 
------------------------
 db_connect.py:  
             
 <connection object at 0x106c98c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:11:46,211 
------------------------
 db_connect.py:  
             
 <connection object at 0x106c98d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:12:02,332 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:12:02,332 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:12:02,332 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:12:02,332 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:12:37,005 
------------------------
 db_connect.py:  
             
 <connection object at 0x107240c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:12:38,738 
------------------------
 db_connect.py:  
             
 <connection object at 0x107240d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:12:40,813 
------------------------
 db_connect.py:  
             
 <connection object at 0x107240c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:12:48,822 
------------------------
 db_connect.py:  
             
 <connection object at 0x10c410c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:12:51,135 
------------------------
 db_connect.py:  
             
 <connection object at 0x10c410d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:12:53,903 
------------------------
 db_connect.py:  
             
 <connection object at 0x10c410c10; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:12:55,527 
------------------------
 db_connect.py:  
             
 <connection object at 0x10c410d60; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/handlers/db_connect.py
------------------------
2022-09-19 19:13:15,971 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:13:15,971 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:13:15,971 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:13:15,971 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:31:33,867 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:31:33,867 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:31:33,867 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:31:33,867 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:42:44,581 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:42:44,581 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:42:44,581 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:42:44,581 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:43:22,469 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:43:22,469 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:43:22,469 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:43:22,469 
------------------------
 extract.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:42,570 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:42,570 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:43,432 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:43,432 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:43,432 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:44,224 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:44,224 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:44,224 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:48:44,224 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Content' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:05,120 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:05,120 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:06,145 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:06,145 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:06,145 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:06,943 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:06,943 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:06,943 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:49:06,943 
------------------------
 extract.py:  
             
 'dict' object has no attribute 'Contents' 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:50:41,974 
------------------------
 extract.py:  
             
 list indices must be integers or slices, not str 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-19 19:50:41,974 
------------------------
 extract.py:  
             
 list indices must be integers or slices, not str 
  @ download_raw_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/extract.py
------------------------
2022-09-20 17:56:10,928 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x103af1fc0; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 18:02:16,796 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100a09fc0; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 18:03:37,239 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10ea31fc0; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 18:05:19,195 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x108595fc0; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:02:44,729 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x109bf2650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:05:35,421 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10d7e6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:06:01,654 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10abee650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:03,020 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:04,363 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:04,363 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:05,648 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:05,648 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:05,648 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:06,906 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:06,906 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:06,906 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:07:06,906 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10306aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:46,049 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:47,968 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:47,968 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:50,130 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:50,130 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:50,130 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0a650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:52,498 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:52,498 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:52,498 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:43:52,498 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x104d0aa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:52,291 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:53,919 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:53,919 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:55,647 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:55,647 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:55,647 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:57,771 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:57,771 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:57,771 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:45:57,771 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c1d6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:32,172 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068da650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:33,733 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068daa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:33,733 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068daa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:35,356 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068da650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:35,356 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068da650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:35,356 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068da650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:37,278 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068daa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:37,278 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068daa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:37,278 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068daa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:46:37,278 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1068daa40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:28,015 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:30,282 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:30,282 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:32,295 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:32,295 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:32,295 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:33,987 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:33,987 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:33,987 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:48:33,987 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10c866a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:10,139 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:11,802 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:11,802 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:13,398 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:13,398 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:13,398 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:15,205 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:15,205 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:15,205 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:51:15,205 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x100892a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:10,338 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:12,316 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:12,316 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:14,138 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:14,138 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:14,138 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:16,336 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:16,336 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:16,336 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-20 23:52:16,336 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x1026c6a40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:19:57,452 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5e650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:00,207 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5ea40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:00,207 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5ea40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:02,379 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5e650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:02,379 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5e650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:02,379 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5e650; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:05,151 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5ea40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:05,151 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5ea40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:05,151 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5ea40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:20:05,151 
------------------------
 db_connect_handler.py:  
             
 <connection object at 0x10df5ea40; dsn: 'user=acnice6032 password=xxx dbname=d2b_assessment host=d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com port=5432', closed: 0> 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:14,243 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:16,843 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:16,843 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:18,002 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:18,002 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:18,002 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:19,553 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:19,553 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:19,553 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-21 00:27:19,553 
------------------------
 db_connect_handler.py:  
             
 connection to server at "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" (3.126.47.113), port 5432 failed: FATAL:  database "d2b_assessments" does not exist
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-22 14:59:54,575 
------------------------
 db_connect_handler.py:  
             
 could not translate host name "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-22 16:32:01,701 
------------------------
 db_connect_handler.py:  
             
 could not translate host name "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known
 
  @ connect: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Handlers/db_connect_handler.py
------------------------
2022-09-22 16:34:09,363 
------------------------
 load.py:  
             
 'dict' object has no attribute 'iterrows' 
  @ load_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/load.py
------------------------
2022-09-22 16:34:26,299 
------------------------
 load.py:  
             
 'int' object has no attribute 'close' 
  @ load_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/load.py
------------------------
2022-09-22 16:34:50,578 
------------------------
 load.py:  
             
 'int' object has no attribute 'close' 
  @ load_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/load.py
------------------------
2022-09-22 16:47:51,637 
------------------------
 load.py:  
             
 tuple indices must be integers or slices, not str 
  @ load_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/load.py
------------------------
2022-09-22 23:53:25,941 
------------------------
 load.py:  
             
 name 'os' is not defined 
  @ load_data: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/load.py
------------------------
2022-09-23 00:56:38,885 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 00:56:38,885 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 00:56:38,885 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 00:56:38,944 
------------------------
 DataLoadServiceProvider.py:  
             
 [Errno 2] No such file or directory: '../Data2bot-Assessment/data/raw//Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/data/raw/orders.csv' 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 00:56:38,944 
------------------------
 DataLoadServiceProvider.py:  
             
 [Errno 2] No such file or directory: '../Data2bot-Assessment/data/raw//Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/data/raw/orders.csv' 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 00:56:38,944 
------------------------
 DataLoadServiceProvider.py:  
             
 [Errno 2] No such file or directory: '../Data2bot-Assessment/data/raw//Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/data/raw/orders.csv' 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 00:59:21,230 
------------------------
 DataLoadServiceProvider.py:  
             
 local variable 'table_name' referenced before assignment 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 00:59:21,230 
------------------------
 DataLoadServiceProvider.py:  
             
 local variable 'table_name' referenced before assignment 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 00:59:21,230 
------------------------
 DataLoadServiceProvider.py:  
             
 local variable 'table_name' referenced before assignment 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 01:00:49,833 
------------------------
 DataLoadServiceProvider.py:  
             
 local variable 'table_name' referenced before assignment 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 01:00:49,833 
------------------------
 DataLoadServiceProvider.py:  
             
 local variable 'table_name' referenced before assignment 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 01:00:49,833 
------------------------
 DataLoadServiceProvider.py:  
             
 local variable 'table_name' referenced before assignment 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/DataLoadServiceProvider.py
------------------------
2022-09-23 01:19:31,271 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:19:31,271 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:19:31,271 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:56:11,853 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:56:11,853 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:56:11,853 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:56:50,367 
------------------------
 ExtractDataServiceProvider.py:  
             
 'Content' 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:56:50,367 
------------------------
 ExtractDataServiceProvider.py:  
             
 'Content' 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:56:50,367 
------------------------
 ExtractDataServiceProvider.py:  
             
 'Content' 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:57:14,253 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:57:14,253 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-23 01:57:14,253 
------------------------
 ExtractDataServiceProvider.py:  
             
 An error occurred (404) when calling the HeadObject operation: Not Found 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/../Data2Bot-Assessment/providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:14,024 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/orders.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:14,024 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/orders.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:14,024 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/orders.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:23,907 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/reviews.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:23,907 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/reviews.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:23,907 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/reviews.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:33,919 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/shipment_deliveries.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:33,919 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/shipment_deliveries.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:33,919 
------------------------
 ExtractDataServiceProvider.py:  
             
 Could not connect to the endpoint URL: "https://d2b-internal-assessment-bucket.s3.amazonaws.com/orders_data/shipment_deliveries.csv" 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/ExtractDataServiceProvider.py
------------------------
2022-09-24 16:08:33,973 
------------------------
 DataLoadServiceProvider.py:  
             
 (psycopg2.OperationalError) could not translate host name "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known

(Background on this error at: https://sqlalche.me/e/14/e3q8) 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/DataLoadServiceProvider.py
------------------------
2022-09-24 16:08:33,973 
------------------------
 DataLoadServiceProvider.py:  
             
 (psycopg2.OperationalError) could not translate host name "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known

(Background on this error at: https://sqlalche.me/e/14/e3q8) 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/DataLoadServiceProvider.py
------------------------
2022-09-24 16:08:33,973 
------------------------
 DataLoadServiceProvider.py:  
             
 (psycopg2.OperationalError) could not translate host name "d2b-internal-assessment-dwh.cxeuj0ektqdz.eu-central-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known

(Background on this error at: https://sqlalche.me/e/14/e3q8) 
  @ execute_service: /Users/cosmoremit/Documents/AcNice/Data2Bot-Assessment/scripts/Providers/DataLoadServiceProvider.py
